### ISSUE TITLE
Update Facebook Graph API to v2.8

### ISSUE THREAD

**Issue by jabranr** [jabranr/socialmedia#41]

**Comment by jonny2plates** [comment]
Can i take this

**Comment by jonny2plates** [comment]
Updates made just need a PR

**Comment by jabranr** [comment]
@jonny2plates Yes, you don't need to ask! Just make sure that you update the tests. ;)

**Comment by jonny2plates** [comment]
it says remote permissions denied?

**Comment by jabranr** [comment]
You cannot make direct changes. You need to fork the repo first and make changes in your own created branch to open a PR. See [guidelines](https://github.com/jabranr/socialmedia/wiki/Contribute) to contribute (ignore the CoffeeScript stuff in there).

**Comment by jabranr** [comment]
@jonny2plates Thank you for the PR. It is now in [latest release](https://github.com/jabranr/socialmedia/releases/tag/2.0.3).

**Comment by jonny2plates** [comment]
Thank you enjoy.
